import { Resource } from './types';

export const mockResources: Resource[] = [
  {
    id: '1',
    name: 'Union Gospel Mission',
    lat: 47.5987,
    lng: -122.3293,
    tags: ['shelter', 'food', 'shower'],
    address: '318 2nd Ave Ext S, Seattle, WA 98104',
    hours: 'Shelter: 7pm–7am daily  •  Meals: 6pm daily',
    description: 'Emergency shelter and services. Dinner served at 6pm sharp.',
    comments: [
      { id: 'c1', text: 'Good hot meals, staff is friendly', addedAt: '2 days ago', accuracyVotes: { accurate: 5, outdated: 0 } },
      { id: 'c2', text: 'Bring your ID if you have one', addedAt: '1 week ago', accuracyVotes: { accurate: 3, outdated: 1 } },
    ],
    addedAt: '3 months ago',
    verified: true,
  },
  {
    id: '2',
    name: 'Capitol Hill Library',
    lat: 47.6218,
    lng: -122.3197,
    tags: ['charging', 'bathroom', 'water'],
    address: '425 Harvard Ave E, Seattle, WA 98102',
    hours: 'Mon–Thu: 10am–8pm  •  Fri–Sat: 10am–6pm  •  Sun: 12pm–6pm',
    description: 'Free outlet charging at tables, public restrooms, water fountain inside.',
    comments: [
      { id: 'c3', text: 'Outlets near the entrance windows, no one bothers you', addedAt: '5 days ago', accuracyVotes: { accurate: 7, outdated: 0 } },
      { id: 'c4', text: 'AC in summer, warm in winter', addedAt: '3 days ago' },
    ],
    addedAt: '1 month ago',
    verified: true,
  },
  {
    id: '3',
    name: 'Denny Park',
    lat: 47.6205,
    lng: -122.3418,
    tags: ['park', 'water'],
    address: 'Denny Way & Dexter Ave N, Seattle, WA 98109',
    hours: '6am–10pm',
    description: 'Generally safe park. Ranger patrols, water fountain near north entrance.',
    comments: [
      { id: 'c5', text: 'Mostly chill, rangers are respectful', addedAt: '2 weeks ago' },
      { id: 'c6', text: 'Water fountain works near north entrance', addedAt: '3 days ago' },
    ],
    addedAt: '2 months ago',
  },
  {
    id: '4',
    name: 'DESC Crisis Solutions Center',
    lat: 47.6017,
    lng: -122.3340,
    tags: ['shelter', 'harm-reduction'],
    address: '1811 Eastlake Ave E, Seattle, WA 98102',
    hours: '24 hours, 7 days a week',
    description: '24/7 crisis stabilization. No questions asked.',
    comments: [
      { id: 'c7', text: 'No judgment, they really help', addedAt: '1 day ago' },
    ],
    addedAt: '3 months ago',
    verified: true,
  },
  {
    id: '5',
    name: 'Pike Place Market Area',
    lat: 47.6087,
    lng: -122.3420,
    tags: ['avoid'],
    address: 'Pike Place Market vicinity',
    hours: 'All hours — avoid especially during market hours',
    description: 'Heavy security presence. Multiple reports of harassment by private security.',
    comments: [
      { id: 'c8', text: 'Got moved on within 5 minutes, avoid during market hours', addedAt: '4 days ago' },
      { id: 'c9', text: 'Security has been very aggressive lately', addedAt: '1 week ago' },
    ],
    addedAt: '6 weeks ago',
  },
  {
    id: '6',
    name: 'I-5 Colonnade Park Overhang',
    lat: 47.6240,
    lng: -122.3360,
    tags: ['covered'],
    address: 'Lakeview Blvd E & E Louisa St',
    hours: 'Always accessible',
    description: 'Covered area under I-5 overpass. Stays dry even in heavy rain.',
    comments: [
      { id: 'c10', text: 'Dry even in heavy rain, good spot', addedAt: '6 days ago' },
    ],
    addedAt: '1 month ago',
  },
  {
    id: '7',
    name: 'Compass Housing Food Bank',
    lat: 47.6030,
    lng: -122.3290,
    tags: ['food', 'water'],
    address: '77 S Washington St, Seattle, WA 98104',
    hours: 'Tue & Thu: 10am–1pm',
    description: 'Community food bank. No ID required.',
    comments: [
      { id: 'c11', text: 'Good variety, lines move fast', addedAt: '3 days ago' },
    ],
    addedAt: '2 months ago',
    verified: true,
  },
  {
    id: '8',
    name: 'REI Co-op Flagship (Propane)',
    lat: 47.6236,
    lng: -122.3355,
    tags: ['propane'],
    address: '222 Yale Ave N, Seattle, WA 98109',
    hours: 'Mon–Sat: 9am–9pm  •  Sun: 10am–7pm',
    description: 'Sells and refills propane canisters. Staff generally friendly.',
    comments: [
      { id: 'c12', text: '1lb canisters ~$6, exchange available', addedAt: '1 week ago' },
    ],
    addedAt: '6 weeks ago',
  },
  {
    id: '9',
    name: 'Belltown Community Center Showers',
    lat: 47.6143,
    lng: -122.3487,
    tags: ['shower', 'bathroom'],
    address: '415 Bell St, Seattle, WA 98121',
    hours: 'Mon–Fri: 8am–12pm (showers)',
    description: 'Free showers available mornings. Towels provided on request.',
    comments: [
      { id: 'c13', text: 'Clean showers, towels if needed', addedAt: '4 days ago' },
      { id: 'c14', text: 'Gets busy around 9am, go early', addedAt: '2 days ago' },
    ],
    addedAt: '5 weeks ago',
    verified: true,
  },
  {
    id: '10',
    name: 'Seattle Central Library',
    lat: 47.6065,
    lng: -122.3321,
    tags: ['wifi', 'charging', 'bathroom', 'water'],
    address: '1000 4th Ave, Seattle, WA 98104',
    hours: 'Mon–Thu: 10am–8pm  •  Fri–Sat: 10am–6pm  •  Sun: 12pm–6pm',
    description: 'Free Wi-Fi, outlets throughout all floors, water fountain and restrooms on each level. No library card needed for Wi-Fi.',
    comments: [
      { id: 'c15', text: 'Wi-Fi is fast and no time limit', addedAt: '3 days ago', accuracyVotes: { accurate: 6, outdated: 0 } },
      { id: 'c16', text: 'Security is generally respectful, warm in winter', addedAt: '1 week ago' },
    ],
    addedAt: '2 months ago',
    verified: true,
  },
  {
    id: '11',
    name: "McDonald's – 3rd & Pike",
    lat: 47.6094,
    lng: -122.3387,
    tags: ['wifi', 'charging', 'bathroom'],
    address: '1400 3rd Ave, Seattle, WA 98101',
    hours: '24/7',
    description: 'Free Wi-Fi, outlets near window seats. Open 24 hours — one of the few spots with overnight Wi-Fi access.',
    comments: [
      { id: 'c17', text: 'Buy a coffee and they leave you alone', addedAt: '2 days ago' },
      { id: 'c18', text: 'Wi-Fi requires accepting terms on a browser — works fine', addedAt: '5 days ago' },
    ],
    addedAt: '3 weeks ago',
  },
];
